"""expiry to appointment, add check later

Revision ID: 128b381a923b
Revises: df3b36fda9e9
Create Date: 2024-01-07 21:09:21.823292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128b381a923b'
down_revision = 'df3b36fda9e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expirty', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('expirty')

    # ### end Alembic commands ###
