"""expiry to appointment, add check later

Revision ID: 18cc3a6ac4c0
Revises: 128b381a923b
Create Date: 2024-01-07 21:09:56.903726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cc3a6ac4c0'
down_revision = '128b381a923b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry', sa.DateTime(), nullable=True))
        batch_op.drop_column('expirty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expirty', sa.DATETIME(), nullable=True))
        batch_op.drop_column('expiry')

    # ### end Alembic commands ###
