"""initial migration, add primary and secondary learning pattern

Revision ID: c33dfc9704f2
Revises: 
Create Date: 2024-01-07 10:40:24.515794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33dfc9704f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_learning_pattern', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('secondary_learning_pattern', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('secondary_learning_pattern')
        batch_op.drop_column('primary_learning_pattern')

    # ### end Alembic commands ###
