"""adding appointment tables

Revision ID: df3b36fda9e9
Revises: 1276da4d31d9
Create Date: 2024-01-07 12:47:59.351546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3b36fda9e9'
down_revision = '1276da4d31d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tutor_feedback', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('is_complete')
        batch_op.drop_column('tutor_feedback')
        batch_op.drop_column('application_status')

    # ### end Alembic commands ###
